_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[0.00058732 0.0004517  0.         0.         0.00705806 0.00081063
          0.00099494 0.00707071 0.         0.00099494]]
_last_original_obs:
    value: |-
        [[0.05883947 0.04522048 0.         0.         0.99643004 0.08133889
          0.1        1.         0.         0.1       ]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x0000016723481010>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 200000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x0000016722FF6660>
_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/train_reacher_v3.py
        e:
            yqbhb54icydaskmjzx1fha8agrmrtkrm:
                codePath: train_reacher_v3.py
                codePathLocal: train_reacher_v3.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1023411220480"
                        used: "109608914944"
                email: krkcdeniz15@gmail.com
                executable: c:\Users\90546\Desktop\reacher_v3\.venv\Scripts\python.exe
                host: DESKTOP-E3OIJ6K
                memory:
                    total: "14773178368"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\90546\Desktop\reacher_v3\train_reacher_v3.py
                python: CPython 3.13.3
                root: C:\Users\90546\Desktop\reacher_v3
                startedAt: "2025-07-10T10:49:17.654311Z"
                writerId: yqbhb54icydaskmjzx1fha8agrmrtkrm
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 22
                - 35
            "4": 3.13.3
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Box(-3.0, 3.0, (2,), float32)
algo:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.1
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.02
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x0000016722FF6660>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001672303ED40>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
normalize_obs:
    value: true
normalize_reward:
    value: true
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (10,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=10, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=10, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=2, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x0000016722FF7620>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1752144561508686800
target_kl:
    value: None
tensorboard_log:
    value: ./ppo_tensorboard/
total_timesteps:
    value: 200000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
